### ISSUE TITLE
競品推薦 Ueli

### ISSUE THREAD

**Issue by watain666** [Inndy/windows-sucks#1]
首先還是要感謝這個 Repo
真的是相見恨晚，不然可以省很多時間在找工具

我要推薦的競品叫 [Ueli](https://ueli.app/#/features) 
他是 Windwos / macOS 跨平台的 App
還有整合 Everything ，兩套實際用下來我覺得 Ueli 比 Wox 好用不少，
缺點是 Ueli 的 Hot Key 綁定限制兩個 Key 組合限制比較多

**Comment by Inndy** [comment]
已加入競品清單，但是我覺得 Wox 用 WPF 更原生，佔用資源跟效能應該都會更好

至於 everything 我個人有設定一個全域快速鍵，這倒是還好 XD
